### ISSUE TITLE
Attribute class and requiered

### ISSUE THREAD

**Issue by Healpiar** [vahidhedayati/ajaxdependancyselection#7]
- The class attribute is not maintained from g:selectXXXX to seletc.
- The required attribute is always true in every g:selectXXXX
- The values to fill a g:selectPrimary can are customize like a g:selectSecondary (controller, action)??

is there a mailing list?

Thanks before ahand!

**Comment by vahidhedayati** [comment]
Hi Healpiar, 

I have been working on a new method that uses websockets rather than AJAX. It is totally secure since all that the backend pushes is JSON result set to each Div:

https://github.com/vahidhedayati/grails-boselecta-plugin

Its awaiting approval / publish 

At the moment is just selectPrimary/selectsecondary

I have re-opened this issue - feel free to let me know if this would be a better solution in your situation
